apiVersion: apps/v1
kind: Deployment
metadata:
  name: overprovisioning-autoscaler
  namespace: default
  labels:
    app: overprovisioning-autoscaler
spec:
  selector:
    matchLabels:
      app: overprovisioning-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: overprovisioning-autoscaler
    spec:
      containers:
        - image: bom.ocir.io/sehubjapacprod/overprovision/autoscaler:latest
          name: autoscaler
          command:
            - /cluster-proportional-autoscaler
            - --namespace=default
            - --expendable-pods-priority-cutoff=-10  
            - --configmap=overprovisioning-autoscaler
            - --default-params={"linear":{"coresPerReplica":1}}
            - --target=deployment/overprovisioning
            - --logtostderr=true
            - --v=2
      imagePullSecrets:
        - name: ocirsecret
      serviceAccountName: cluster-proportional-autoscaler-example
